TextToImage:
  DreamShaperXL:
    target: generation_models.StableDiffusionXLTextToImage
    params:
      checkpoint_file: "checkpoints/DreamShaperXL.safetensors"
      download_url: "https://civitai.com/api/download/models/354657"
      scheduler: "dpm++sde_karras"
  SDXLTurbo:
    target: generation_models.StableDiffusionXLTextToImage
    params:
      checkpoint_file: "checkpoints/SDXLTurbo.safetensors"
      download_url: "https://huggingface.co/stabilityai/sdxl-turbo/resolve/main/sd_xl_turbo_1.0_fp16.safetensors?download=true"
  AnimeV3:
    target: generation_models.StableDiffusionXLTextToImage
    params:
      checkpoint_file: "checkpoints/AnimeV3.safetensors"
      download_url: "https://civitai.com/api/download/models/173961"
      scheduler: "dpm++2m_karras"
ImageToImage:
  DreamShaperXL:
    target: generation_models.StableDiffusionXLImageToImage
    params:
      checkpoint_file: "checkpoints/DreamShaperXL.safetensors"
      download_url: "https://civitai.com/api/download/models/354657"
      scheduler: "dpm++sde_karras"
ControlNetTextToImage:
  DreamShaper:
    target: generation_models.StableDiffusionControlNetTextToImage
    params:
      checkpoint_file: "checkpoints/DreamShaper.safetensors"
      download_url: "https://civitai.com/api/download/models/128713?type=Model&format=SafeTensor&size=pruned&fp=fp16"
      scheduler: "euler_a"
