RealisticVision:
  target: dependency_modules.rewarding.models.StableDiffusion
  params:
    checkpoint_file: "checkpoints/RealisticVision.safetensors"
    download_url: "https://civitai.com/api/download/models/130072?type=Model&format=SafeTensor&size=pruned&fp=fp16"
    scheduler: "dpm++2m"
SDXLTurbo:
  target: dependency_modules.rewarding.models.StableDiffusionXL
  params:
    checkpoint_file: "checkpoints/SDXLTurbo.safetensors"
    download_url: "https://huggingface.co/stabilityai/sdxl-turbo/resolve/main/sd_xl_turbo_1.0_fp16.safetensors?download=true"
RealitiesEdgeXL:
  target: dependency_modules.rewarding.models.StableDiffusionXL
  params:
    checkpoint_file: "checkpoints/RealitiesEdgeXL.safetensors"
    download_url: "https://civitai.com/api/download/models/294995"
    scheduler: "dpm++2m_karras"
AnimeV3:
  target: dependency_modules.rewarding.models.StableDiffusionXL
  params:
    checkpoint_file: "checkpoints/AnimeV3.safetensors"
    download_url: "https://civitai.com/api/download/models/173961"
    scheduler: "dpm++2m_karras"
